# deploy on Docker swarm cluster
# docker stack deploy -c docker-compose.swarm.yml openfactory

services:
  asset-api:
    image: ofa/asset-api
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    environment:
      KSQLDB_URL: ${KSQLDB_URL}
    ports:
      - target: 5555
        published: 5555
        protocol: tcp
        mode: ingress
